#! /bin/sh
#=========================================================
#
#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#                                             
#=========================================================

sxhkd &
picom &
xrandr -s 1366x768 &
#feh --bg-scale $HOME/Pictures/wallpaper.jpg &
feh --bg-scale $HOME/Pictures/cyberpunk-2077-10-1366×768.jpg &
$HOME/.config/polybar/launch.sh & 

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a code desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Synclient
